project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ProductsView.as_view(), name='main')
]

project/main/models.py
from django.db import models
from django.utils import timezone


class Products(models.Model):
    name = models.CharField(unique=True, max_length=100, null=False, blank=False)
    price = models.FloatField()
    image_url = models.URLField(max_length=100000)
    creator = models.CharField(max_length=100)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.pk})"

project/main/forms.py
from django import forms


class ProductForm(forms.Form):
    image_url = forms.CharField(max_length=100000, label='Enter URL to image')
    name = forms.CharField(max_length=100, label='Enter product name')
    price = forms.FloatField(label='Enter price')
    creator = forms.CharField(max_length=100, label='Enter your username')
    create_date = forms.DateTimeField(label='Enter product creation date and time')

project/main/views.py
from django.contrib.auth import models
from rest_framework import viewsets, permissions, views
from .serializers import UserSerializer, GroupSerializer
from .models import Products
from rest_framework.response import Response
from django.template.defaulttags import register
from rest_framework.renderers import TemplateHTMLRenderer
from datetime import datetime
from dateutil import parser as datetime_parser
import math
import uuid
from .forms import ProductForm
import pytz


# Template tags and filters

@register.simple_tag
def generate_uuid4():
    return uuid.uuid4()

@register.simple_tag
def get_product_form(pk):
    """
    Get Product form with initial model data.
    """
    try:
        pk = int(pk)
        product = Products.objects.get(pk=pk)

        return ProductForm(initial={
            'image_url': product.image_url,
            'name': product.name,
            'price': product.price,
            'creator': product.creator,
            'create_date': product.create_date
        })
    except Products.DoesNotExist:
        pass

@register.simple_tag
def get_now_datetime():
    """
    Get current datatime without timezone info.
    """
    dt_str = str(datetime_parser.isoparse(str(datetime.now())))
    dt_str = dt_str[:dt_str.find('.')]
    return datetime.strptime(dt_str, '%Y-%m-%d %H:%M:%S')


@register.filter
def get_dict_key_by_index(d: dict, i: int) -> str:
    return list(d.keys())[i]

@register.filter
def get_dict_value(key, d: dict):
    return d[key]

# Default views

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = models.User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = models.Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

# User defined functions and views

class ProductsView(views.APIView):
    template_name = 'index.html'
    permission_classes = [permissions.AllowAny]
    renderer_classes = [TemplateHTMLRenderer]
    path = {'/': 'Main page'}
    data_title = 'Click to change...'
    product_form = ProductForm
    
    def separate_products(self, products, cols=4):
        """
        Separate list of Products into list of lists with length == specified columns (cols).
        """
        sep_prods = []
        prods = []
        start_index = 0

        for row in range(math.ceil(len(products) / cols)):
            for product in products[start_index:start_index+cols]:
                prods.append(product)
            sep_prods.append(prods.copy())
            prods.clear()
            start_index += cols
        
        return sep_prods

    def get_basic_context(self):
        return {
            'path': self.path,
            'products': self.separate_products(Products.objects.all()),
            'data_title': self.data_title,
            'product_form': self.product_form,
        }

    def get_parsed_datetime_string(self, string):
        return datetime_parser.parse(datetime.strptime(
            string, '%Y-%m-%d %H:%M:%S').replace(tzinfo=pytz.UTC).isoformat())

    # Getting all products
    def get(self, request):
        return Response(self.get_basic_context())

    # Create and update product
    def post(self, request):
        if 'pk' in request.POST:
            # Update product
            if request.POST['pk'] != 'create':
                try:
                    product = Products.objects.get(pk=request.POST['pk'])

                    product.image_url = request.POST['image_url']
                    product.name = request.POST['name']
                    product.price = request.POST['price']
                    product.creator = request.POST['creator']
                    product.create_date = self.get_parsed_datetime_string(request.POST['create_date'])

                    product.save()
                except Products.DoesNotExist:
                    pass
            # Create product
            else:
                Products.objects.create(
                    image_url=request.POST['image_url'],
                    name=request.POST['name'],
                    price=request.POST['price'],
                    creator=request.POST['creator'],
                    create_date=self.get_parsed_datetime_string(request.POST['create_date'])
                )
        
        return Response(self.get_basic_context())

    # Delete product
    def delete(self, request):
        try:
            Products.objects.get(pk=request.POST['pk']).delete()
        except Products.DoesNotExist:
            pass

        return Response(self.get_basic_context())

project/templates/index.html
{% extends 'layout.html' %}


{% block header %}
    <style>
        #products {
            border: 1px solid rgba(185, 185, 185, 0.466);
            box-shadow: 5px 5px rgb(230, 230, 230);
            padding: 15px;
        }

        .row {
            margin: auto;
            width: 97%;
            display: flex;
            justify-content: center;
        }

        .col-sm-3 {
            border: 2px solid lightgrey;
            border-radius: 25px;
            padding: 10px;
            margin: 5px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            text-align: center;
        }

        .hidden-container {
            display: none;
        }

        .product-form-hidden {
            font-size: 13px;
            flex-direction: column;
            justify-content: center;
        }

        .product-data {
            margin-bottom: 5px;
        }

        .product-image {
            margin-bottom: 15%;
        }
        
        .product-image img {
            width: 100%;
            height: auto;
            max-height: 15%;
        }
        
        .product-text-data {
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-bottom: 15%;
        }

        .product-text-data div {
            margin: 2px;
        }

        .product-name {
            font-weight: 600;
            font-size: 20px;
            line-height: 22px;
        }

        .product-data input {
            margin-bottom: 10px;
        }

        .product-form-input {
            max-width: 100%;
        }

        .action-buttons input {
            font-weight: 700;
            width: 100%;
            margin: 1px;
            height: 50px;
            border-radius: 20px;
            font-size: 12px;
        }

        .update-button {
            background-color: rgb(0, 190, 0);
        }

        .delete-button {
            background-color: rgb(228, 0, 0);
        }

        #create-product-container {
            margin-top: 15px;
            width: 100%;
        }

        #create-product-form {
            background-color: rgba(144, 238, 144, 0.445);
            padding: 15px;
            margin-bottom: 0px;
        }

        #create-product-form h1 {
            background-color: lightgreen;
            padding: 10px;
            margin-bottom: 15px;
            text-align: center;
        }

        #create-product-form p {
            display: flex;
            justify-content: center;
        }

        #create-product-form p label {
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin: 0px;
        }

        #create-product-form p * {
            width: 100%;
            font-size: 15px;
        }

        #create-button {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
            padding: 15px;
            border-radius: 40px;
            font-size: 20px;
            background-color: rgb(0, 216, 0);
        }
    </style>
{% endblock %}


{% block content %}
    <div id="products">
        <div class="hidden-container" id="products-not-found">
            <img src="https://cdn-icons-png.flaticon.com/128/4076/4076503.png"
                style="display: block; margin-left: auto; margin-right: auto; width: 10%;">
            <h1 style="text-align: center; margin-top: 10px;">At the moment there are no products...</h1>
        </div>

        {% if products|length > 0 %}
            {% for row in products %}
                <div class="row flex-nowrap">
                    {% for product in row %}
                        <input type="hidden" value="{% generate_uuid4 %}" id="form-id-{{ product.pk }}">
                        <form action="{% url 'main' %}" method="POST" class="col-sm-3" onclick="this.id = getProductUuid4('form-id-{{ product.pk }}')" onmouseleave="hideProductForm('{{ product.pk }}')">
                            <input type="hidden" value="{{ product.pk }}" name="pk">
                            
                            <div class="product-data" id="product-data-{{ product.pk }}" onclick="showProductForm('{{ product.pk }}')">
                                <div class="product-form-hidden hidden-container" id="product-form-{{ product.pk }}">
                                    {% get_product_form product.pk %}
                                </div>

                                <div class="product-image" id="product-image-{{ product.pk }}" title="{{ data_title }}"><img src="{{ product.image_url }}" title="{{ data_title }}"></div>
                                
                                <div class="product-text-data col" title="{{ data_title }}">
                                    <div class="product-name" id="product-name-{{ product.pk }}">{{ product.name }}</div>
                                    <div class="product-price" id="product-price-{{ product.pk }}" style="font-family: 'Courier New', Courier, monospace; font-size: 25px; letter-spacing: 0.1px;">{{ product.price }}</div>
                                    <div class="product-creator" id="product-creator-{{ product.pk }}" style="font-size: 15px;">&check; {{ product.creator }}</div>
                                    <div class="product-create-date" id="product-create-date-{{ product.pk }}" style="font-size: 13px;">&#8986; {{ product.create_date }}</div>
                                </div>
                            </div>

                            <div class="action-buttons">
                                <input type="submit" value="Update" class="update-button" onclick="updateProduct('{{ product.pk }}')">
                                <input type="button" value="Delete" class="delete-button" onclick="deleteProduct('{{ product.pk }}')">
                            </div>
                        </form>
                    {% endfor %}
                </div>
            {% endfor %}
        {% else %}
            <img src="https://cdn-icons-png.flaticon.com/128/4076/4076503.png" style="display: block; margin-left: auto; margin-right: auto; width: 10%;">
            <h1 style="text-align: center; margin-top: 10px;">At the moment there are no products...</h1>
        {% endif %}

        <div class="row flex-nowrap" id="create-product-container">
            <form action="{% url 'main' %}" method="POST" id="create-product-form">
                <input type="hidden" value="create" name="pk">
                <h1>Create new product</h1>
                {{ product_form.as_p }}
                <input type="submit" value="Create" id="create-button">
            </form>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script type="text/javascript">
        if (window.history.replaceState) {
                window.history.replaceState(null, null, window.location.href);
            }


        var createDate = document.querySelector('#create-product-form #id_create_date')
        createDate.value = '{% get_now_datetime %}'


        function getProductFormAndFields(id) {
            var form = document.getElementById(`product-form-${id}`);
            var fields = document.querySelectorAll(`#product-image-${id}, #product-name-${id}, #product-price-${id}, #product-creator-${id}, #product-create-date-${id}`);

            var map = new Map();
            map.set('form', form);
            map.set('fields', fields);
            return map
        };

        function showProductForm(id) {
            var data = getProductFormAndFields(id);
            var form = data.get('form');
            var fields = data.get('fields');

            if (form.style.display === 'flex') {
                document.getElementById(`product-data-${id}`).setAttribute('onclick', '')
            } else {
                for (let i = 0; i < fields.length; i++) {
                    fields[i].style.display = 'none'
                };

                form.style.display = 'flex'

                var allFields = document.querySelectorAll('input[name="image_url"], input[name="name"], input[name="price"], input[name="creator"], input[name="create_date"]');

                for (let i = 0; i < allFields.length; i++) {
                    allFields[i].classList.add('product-form-input');
                    if (isNaN(allFields[i].id.slice(-1))) {
                        allFields[i].id += `_${id}`
                    }
                };
            }
        };

        function isSpaceString(str) {
            if (!str.replace(/\s/g, '').length) {
                return true
            } else {
                return false
            }
        };

        var productsData = document.getElementsByClassName('product-data');
        for (let i = 0; i < productsData.length; i++) {
            productsData[i].addEventListener('mouseenter', function() {
                var productsForms = document.getElementsByClassName('product-form-hidden');

                if (productsForms[i].style.display == 'none' && productsData[i].getAttribute('onclick') == null || isSpaceString(productsData[i].getAttribute('onclick')) || productsData[i].getAttribute('onclick') === 'undefined') {
                    var id = productsData[i].id;
                    var pk = new String()
                    for (let si = 0; si < id.length; si++) {
                        if (!isNaN(id[si])) {
                            pk += id[si]
                        }
                    };
                    productsData[i].setAttribute('onclick', showProductForm(pk))
                }
            })
        };

        function hideProductForm(id) {
            var data = getProductFormAndFields(id);
            var form = data.get('form');
            var fields = data.get('fields');

            form.style.display = 'none';
            for (let i = 0; i < fields.length; i++) {
                fields[i].style.display = 'block'
            }
        };

        function sendRequest(url, method, data) {
            const XHR = new XMLHttpRequest(),
                FD = new FormData();

            // Push our data into our FormData object
            for (name in data) {
                FD.append(name, data[name]);
            }

            // // Define what happens on successful data submission
            // XHR.addEventListener('load', function (event) {
            //     alert('Yeah! Data sent and response loaded.');
            // });

            // // Define what happens in case of error
            // XHR.addEventListener(' error', function (event) {
            //     alert('Oops! Something went wrong.');
            // });

            // Set up our request
            XHR.open(method, url);

            // Send our FormData object; HTTP headers are set automatically
            XHR.send(FD);

            // _callback();
        };

        function getProductUuid4(id) {
            return document.querySelector(`input[id='${id}']`).value
        };

        function updateProduct(id) {
            sendRequest(
                document.getElementById(getProductUuid4(`form-id-${id}`)).action,
                'POST',
                {
                    'pk': id,
                    'image_url': document.getElementById(`id_image_url_${id}`).value,
                    'name': document.getElementById(`id_name_${id}`).value,
                    'price': document.getElementById(`id_price_${id}`).value,
                    'creator': document.getElementById(`id_creator_${id}`).value,
                    'create_date': document.getElementById(`id_create_date_${id}`).value,
                }
            )
        };

        async function deleteProduct(id) {
            if (document.getElementById(getProductUuid4(`form-id-${id}`)) !== null) {
                var form = document.getElementById(getProductUuid4(`form-id-${id}`));

                sendRequest(
                    form.action,
                    'DELETE',
                    {'pk': id}
                );

                form.style.display = 'none'
            } else {
                await new Promise(r => setTimeout(r, 1000));
                deleteProduct(id)
            }
        };
    </script>
{% endblock %}

project/templates/layout.html
{% load static %}


<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="robots" content="NONE,NOARCHIVE">
        <meta name="viewport" content="width=device-width initial-scale=1">

        <title>Products – {{ path|get_dict_key_by_index:-1|get_dict_value:path }}</title>

        <link rel="stylesheet" type="text/css" href="/static/rest_framework/css/bootstrap.min.css">
        
        <!-- Connecting Bootstrap -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
        
        <style>
            .breadcrumb {
                font-size: 20px;
                margin: 15px;
            }

            #content {
                margin: 15px;
            }

            .jsonwidget {
                margin: 15px;
                max-height: 80%;
            }

            .jsonwidget textarea {
                width: 100%;
                max-width: 100%;
                max-height: inherit;
            }

            .jsonwidget div {
                width: 100%;
                max-width: 100%;
                max-height: inherit;
            }
        </style>

        {% block header %}
        {% endblock %}
    </head>

    <body>

        <div>
            <div>
                <ul class="breadcrumb">

                    {% for url, title in path.items %}
                        <li class="active"><a href="{{ url }}">{{ title }}</a></li>
                    {% endfor %}

                </ul>


                <!-- Content -->
                <div id="content" role="main" aria-label="content">

                    {% block content %}
                    {% endblock %}

                </div><!-- /.content -->
            </div><!-- /.container -->
        </div><!-- ./wrapper -->

        <script>
            window.drf = {
                csrfHeaderName: "X-CSRFTOKEN",
                csrfToken: "bLlud3Co4zB5Z1VT4PtSuAAPYJIftnkPi0i9C3D7gSIJyP1fBOvH7fTHiH6vmeWQ"
            };
        </script>
        <script src="/static/rest_framework/js/jquery-3.5.1.min.js"></script>
        <script src="/static/rest_framework/js/ajax-form.js"></script>
        <script src="/static/rest_framework/js/csrf.js"></script>
        <script src="/static/rest_framework/js/bootstrap.min.js"></script>
        <script src="/static/rest_framework/js/prettify-min.js"></script>
        <script src="/static/rest_framework/js/default.js"></script>
        <script>
            $(document).ready(function () {
                $('form').ajaxForm();
            });
        </script>

        {% block scripts %}
        {% endblock %}

    </body>
</html>